books:
  title: Encyclopedia Blanktopia
  author: chendol
  pages:
    help:
      - |2
               Welcome to
              &9&lBlanktopia&r

        1. [&1&nRules](/help rules hover=Read the rules of the server.)
        2. [&1&nAbout](/help about hover=Find out what makes Blanktopia unique!)
        3. [&1&nCommands](/help commands hover=Learn the important commands!)
        4. [&1&nDiscord](/help discord hover=Join us on Discord!)
        5. [&1&nClaiming](run_command=/help claims hover=Protect your builds by claiming!)
        6. [&1&nEnchantments](run_command=/help enchantments hover=Read about our custom enchantments!)
        7. [&1&nPlayer Shops](run_command=/help shops hover=Learn how to set up your own shops!)
        8. [&1&nVoting](run_command=/help vote hover=Support the server by voting!)
        9. [&1&nRanks](/help ranks hover=Rank up and gain more perks!)
        10. [&1&nTechnical](/help technical hover=Technical information for technical players.)

    'tutorial build':
      - |
        [Blanktopia](color=#486aa8 bold) [Build](color=#86a8e7 bold) [Friendly Reminder](color=#486aa8 bold)
        [------------](color=#486aa8 bold)

        [Please look around your build site and try to keep at least 100 blocks away from other players' creations.](color=#486aa8)

        [Thanks for being a considerate builder!](color=#486aa8)

    'tutorial grief':
      - |
        [Blanktopia](color=#486aa8 bold) [Grief](color=#86a8e7 bold) [Friendly Reminder](color=#486aa8 bold)
        [------------](color=#486aa8 bold)

        [Destroying people's builds, even if unclaimed, is griefing and will result in a ](color=#486aa8)[30-day ban](color=#ff3849).

        [Find a base? Let it be.](color=#486aa8)

        [See /rules](color=#486aa8 bold)

    'tutorial crafting':
      - |
        [Blanktopia](color=#486aa8 bold) [Grief](color=#86a8e7 bold) [Friendly Reminder](color=#486aa8 bold)
        [------------](color=#486aa8 bold)

        [Right-click on a crafting table in your inventory to use it directly!](color=#486aa8)

        [We have some custom recipes! You can find all of them in your recipe book.](color=#486aa8)

    'tutorial enderchest':
      - |
        [Blanktopia](color=#486aa8 bold) [Grief](color=#86a8e7 bold) [Friendly Reminder](color=#486aa8 bold)
        [------------](color=#486aa8 bold)

        [Right-click on an ender chest in your inventory to use it directly!](color=#486aa8)

        [We have an additional three rows of ender chest space in Blanktopia!](color=#486aa8)
    rules:
      - |
        **Rules**
        We have some basic rules so everyone can have fun:
        &41. Be respectful&r
        We're here to have fun, so don't be rude!
        &42. No Griefing&r
        If it's not yours, don't touch it.
        &43. Earn Your Items&r
        Cheats, hacks, and x-rays make the game unfair
      - |
        &44. Mind Your Lag&r
        Be mindful of server lag, keep your farms compact.
        &45. No Bypassing AFK&r
        Auto-clickers, AFK pools, etc. are not allowed.
        &46. Staff Has Final Say&r
        Our code of conduct is to be kind, helpful, fair, and respectful.
        [&1&l« Back](/help hover=Back to Contents)

    discord:
      - |
        **Links**
        Here are some useful links:

        [&1&nDiscord](https://discord.gg/XPUNkut)
        [&1&nWorld Map](https://map.blanktopia.com/)
        [&1&nDonation](https://store.blanktopia.com/)
        [&1&nVote](https://minecraft-mp.com/server/247958/vote/)

        [&1&l« Back](/help hover=Back to Contents)

    about:
      - |
        **About**
        Here are some unique changes we have:

        1. [&1&nTeleporting](/help teleport hover=Find out how to teleport!).
        2. [&1&nEnchantments](/help enchantments hover=Read about our custom enchantments!).
        3. [&1&nPlayer shops](/help shops hover=Learn how to set up your own shops!).
        4. Only one person needs to sleep.
        5. Trees drop instantly when chopped!
        6. Ender dragon drops an elytra and a dragon egg on death.
      - |
        7. Right click with a slime ball to find slime chunks.
        8. Use crafting tables, ender chests, and shulker boxes from your inventory.

        [&1&l« Back](/help hover=Back to Contents)

    shop:
      - |
        **Player Shops**
        [&1&nSpawn Rules](/help shops rules hover=Rules for shops in spawn)
        To make a shop, place a sign on a barrel that matches this format:

        &7Line 1:&r [Shop]
        &7Line 2:&r <description>
        &7Line 3:&r <cost e.g. 1 diamond>
        &7Line 4:&r <blank>

        Make sure your barrel is in a [&1&nclaimed region](/help claims hover=How to claim regions)!
        [&1&l« Back](/help hover=Back to Contents)

    shops:
      - |
        **Player Shops**
        [&1&nSpawn Rules](/help shops rules hover=Rules for shops in spawn)
        To make a shop, place a sign on a barrel that matches this format:

        &7Line 1:&r [Shop]
        &7Line 2:&r <description>
        &7Line 3:&r <cost e.g. 1 diamond>
        &7Line 4:&r <blank>

        Make sure your barrel is in a [&1&nclaimed region](/help claims hover=How to claim regions)!
        [&1&l« Back](/help hover=Back to Contents)

    'shops rules':
      - |
        **Spawn Rules**
        &41. Max 15 blocks tall.&r
        &42. No reselling.&r
        &43. No powered beacons, redstone clocks, minecarts.&r
        &44. Max 1 entity excluding armorstands/item frames&r
        &45. Max 2 hoppers.&r
        &46. No scamming!&r
        [&1&l« Back](/help hover=Back to Contents)


    claims:
      - |
        **Claiming**
        Right click two corners of a rectangle to claim:

          &6#&7----+
          |        |
          +----&6#&r

        Use &6/trust&r to allow friends to build in your claims.

        [&1&l« Back](/help hover=Back to Contents)

    vote:
      - |
        **Voting**
        Voting helps us attract new users. Click on the link below to vote!

        [&1&nClick here to vote](https://minecraft-mp.com/server/247958/vote/ Click here to vote)

        If you're having fun, invite your friends to join us!

        [&1&l« Back](/help hover=Back to Contents)

    ranks:
      - |
        **Ranks**
        Gain more [&1&nhomes](/help commands hover=Find out how to teleport!) and [&1&nclaim blocks](/help claims hover=How to claim regions) by [&1&nvoting](/help vote hover=Support the server by voting!). Hover over the ranks!
        &7000&r votes: [Hamster](color=#d68a8c hover=3 homes
        Max 1000 claim blocks)
        &700&r1 votes: [Squirrel](color=#df9d8a hover=5 homes
        Max 2000 claim blocks)
        &700&r3 votes: [Rabbit](color=#e8b089 hover=10 homes
        Max 4000 claim blocks)
        &700&r9 votes: [Hedgehog](color=#f1c387 hover=15 homes
        Max 8000 claim blocks)
        &70&r18 votes: [Kitten](color=#f8d786 hover=20 homes
        Max 16000 claim blocks)
        &70&r36 votes: [Koala](color=#dff086 hover=30 homes
        Max 32000 claim blocks)
        &70&r60 votes: [Panda](color=#c2f496 hover=40 homes
        Max 64000 claim blocks)
      - |
        &70&r90 votes: [Penguin](color=#a4f8a6 hover=50 homes
        Max 128000 claim blocks)
        &r120 votes: [Seahorse](color=#87fdb6 hover=60 homes
        Max 256000 claim blocks)
        &r160 votes: [Dolphin](color=#82ffd5 hover=70 homes
        Max 512000 claim blocks)
        &r210 votes: [Orca](color=#7affeb hover=80 homes
        Max 768000 claim blocks)
        &k999&r votes: [Fox](color=#7999f7 hover=chendol's the owner of the server!)
        [&1&l« Back](/help hover=Back to Contents)

    commands:
      - |
        **Commands**
        1. [&1&nTeleport](/help commands teleport hover=Teleportation-related commands)
        2. [&1&nChat](/help commands chat hover=Communication-related commands)
        3. [&1&nClaims](/help commands claims hover=Claim-related commands)
        4. [&1&nQuality of Life](/help commands qol hover=Useful utility commands)
        5. [&1&nPatrons](/help commands patrons hover=Commands for patrons)
        [&1&l« Back](/help hover=Back to Contents)

    commands qol:
      - |
        **QoL Commands**
        Hover:
        [/search <item>](color=6 hover=Searches nearby chests for items)
        [/unload](color=6 hover=Places matching items into nearby chests)
        [/dump](color=6 hover=Places all items into nearby chests)
        [/blacklist <item>](color=6 hover=Blacklists item from being picked up)
        [/besttools](color=6 hover=Automatically use the best tool to break blocks)
        [/refill](color=6 hover=Automatically refill your hand from your inventory)
        [/quest](color=6 hover=Display your current quest status)
        [&1&l« Back](/help commands hover=Back to Commands)

    commands teleport:
      - |
        **Teleport Commands**
        Hover:
        [/back](color=6 hover=Teleport to your previous location)
        [/resource](color=6 hover=Teleport to the resource world which gets reset occasionally. Gather your resources here!)
        [/nether](color=6 hover=Teleport to the resource nether which gets reset occasionally. Gather your resources here!)
        [/sethome <name>](color=6 hover=Saves a teleport location)
        [/home <name>](color=6 hover=Teleport to previously saved location)
        [/tpa <who>](color=6 hover=Teleport to a friend)
        [/tpahere <who>](color=6 hover=Teleport a friend here)
        [/wild](color=6 hover=Teleport to somewhere random)
        [/warp \[name\]](color=6 hover=Teleport to spawn/shops/crates)
        [&1&l« Back](/help commands hover=Back to Commands)

    commands chat:
      - |
        **Chat Commands**
        Hover:
        [/afk](color=6 hover=Toggles your AFK status. AFK players cannot move or take damage.)
        [/g](color=6 hover=Switch to the global channel. Everyone can hear you here.)
        [/l](color=6 hover=Switch to the local channel. Only players within 200 blocks can hear you.)
        [/w <who> <msg>](color=6 hover=Whisper to a friend)
        [/r <msg>](color=6 hover=Reply a whisper)
        [/mail send <who> <msg>](color=6 hover=Sends a message to an offline player)
        [/party help](color=6 hover=Create a party group chat)
        [/sit](color=6 hover=Sit on the floor)
        [/lay](color=6 hover=Lay on the floor)
        [&1&l« Back](/help commands hover=Back to Commands)

    commands claims:
      - |
        **Claims Commands**
        Hover:
        [/trustlist](color=6 hover=List trusted players in your claim)
        [/accesstrust <who|public>](color=6 hover=Allows a player or everyone to open doors and use buttons in your claim)
        [/containertrust <who|public>](color=6 hover=Allows a player or everyone to open containers in your claim)
        [/trust <who|public>](color=6 hover=Allows a player or everyone to build in your claim)
        [/untrust <who|public>](color=6 hover=Revokes trust to players or everyone)
        [/permissiontrust <who|public>](color=6 hover=Allows a player or everyone to change permissions in your claim)
        [/expandclaim <number>](color=6 hover=Expand your claim in the direction you are looking)
      - |
        [/unclaim](color=6 hover=Unclaims the area you are standing in)
        [/givepet](color=6 hover=Gives a pet to another player)
        [&1&l« Back](/help commands hover=Back to Commands)

    commands patrons:
      - |
        **Patron Commands**
        Hover:
        [/star](color=6 hover=Toggles star suffix in your name)
        [/nick <name>](color=6 hover=Sets a colourable nickname)
        [/colours](color=6 hover=Learn how to format your nickname with colours)
        [/pet](color=6 hover=Have a permanent pet follow you around!)
        [&1&l« Back](/help commands hover=Back to Commands)

    technical:
      - |
        **Technical**
        &4Per-Player Mob Cap:
        &r12 hostile, 9 passive
        &4Per-Type Mob Cap:
        &r24 in 32 blocks
        &4Despawn range:
        &r32 soft, 64 hard
        &4Activation range:
        &r32 hostile, 16 else
        &4Entity cramming limit:
        &r8 (no drops)
        &4Portals don't load chunks.
        &4Beds don't explode.
      - |
        &4TNT duping/bedrock breaking patched.
        
        [&1&l« Back](/help about hover=Back to About)

    enchantments:
      - |
        **Custom Enchantments**
        Use an enchanting table to get one of these enchantments!

        ● [&1&nSoulbound](run_command=/help enchantments soulbound hover=Will not drop on death.
        Rarity: &5Legendary&r
        Found on: All
        Enchantable on: All)
        ● [&1&nNight Vision](/help enchantments nightvision hover=See in the dark.
        Rarity: &1Rare&r
        Found on: Helmets
        Enchantable on: Helmets)
        ● [&1&nSpring](/help enchantments spring hover=Jump higher with every jump!
        Rarity: &2Uncommon&r
        Found on: Leggings
        Enchantable on: Leggings)
        ● [&1&nStride](/help enchantments stride hover=Walk faster!
        Rarity: &2Uncommon&r
        Found on: Boots
        Enchantable on: Boots)
        ● [&1&nSmelt](/help enchantments smelt hover=Smelts the blocks you mine.
        Rarity: &1Rare&r
        Found on: Pickaxes
        Enchantable on: Pickaxes, Axes, Shovels)
        ● [&1&nBeheading](/help enchantments beheading hover=Gives a chance of dropping mob heads.
        Rarity: &1Rare&r
        Found on: Axes
        Enchantable on: Axes)
        ● [&1&nFrost](/help enchantments frost hover=Slows the target
        Rarity: &2Uncommon&r
        Found on: Swords, Axes
        Enchantable on: Swords, Axes)
        ● [&1&nSting](/help enchantments sting hover=Poisons the target
        Rarity: &2Uncommon&r
        Found on: Swords, Axes
        Enchantable on: Swords, Axes)
      - |
        ● [&1&nHarvest](/help enchantments harvest hover=Automatically replant crops
        Rarity: &1Rare&r
        Found on: Hoes
        Enchantable on: Swords, Axes)
        ● [&1&nSpectral](/help enchantments spectral hover=Make the target glow
        Rarity: &1Rare&r
        Found on: Swords, Axes
        Enchantable on: Swords, Axes)
        ● [&1&nSniper](/help enchantments sniper hover=Fire arrows faster and further
        Rarity: &2Uncommon&r
        Found on: Bows, Crossbows
        Enchantable on: Bows, Crossbows)
        ● [&1&nParry](/help enchantments sniper hover=Grants Strength after blocking a hit
        Rarity: &2Uncommon&r
        Found on: Shield
        Enchantable on: Shield)
        ● [&1&nRush](/help enchantments sniper hover=Grants Speed after blocking a hit
        Rarity: &2Uncommon&r
        Found on: Shield
        Enchantable on: Shield)
        ● [&1&nFinal](/help enchantments final hover=Cannot be modified on an anvil.
        Rarity: Common
        Found on: Unobtainable
        Enchantable on: All)

        [&1&l« Back](/help hover=Back to Contents)

    'enchantments soulbound':
      - |
        **Soulbound**
        ##Will not drop on death.##

        Rarity: &5Legendary&r
        Found on: All
        Enchantable on: All

        [&1&l« Back](/help enchantments hover=Back to Enchantments)

    'enchantments nightvision':
      - |
        **Night Vision**
        ##See in the dark.##

        Rarity: &1Rare&r
        Found on: Helmets
        Enchantable on: Helmets)

        [&1&l« Back](/help enchantments hover=Back to Enchantments)

    'enchantments spring':
      - |
        **Spring**
        ##Jump higher with every jump!##

        Rarity: &2Uncommon&r
        Max Level: III
        Found on: Leggings
        Enchantable on: Leggings

        [&1&l« Back](/help enchantments hover=Back to Enchantments)

    'enchantments stride':
      - |
        **Stride**
        ##Walk faster!##

        Rarity: &2Uncommon&r
        Max Level: V
        Found on: Boots
        Enchantable on: Boots

        [&1&l« Back](/help enchantments hover=Back to Enchantments)

    'enchantments smelt':
      - |
        **Smelt**
        ##Smelts the blocks you mine.##

        Rarity: &1Rare&r
        Found on: Pickaxes
        Enchantable on: Pickaxes, Axes, Shovels

        [&1&l« Back](/help enchantments hover=Back to Enchantments)

    'enchantments beheading':
      - |
        **Beheading**
        ##Gives a chance of dropping mob heads.##

        Rarity: &1Rare&r
        Max Level: V
        Found on: Axes
        Enchantable on: Axes

        [&1&l« Back](/help enchantments hover=Back to Enchantments)

    'enchantments frost':
      - |
        **Frost**
        ##Slows the target##

        Rarity: &2Uncommon&r
        Max Level: III
        Found on: Swords, Axes
        Enchantable on: Swords, Axes
        Conflicts with: Fire Aspect, Sting

        [&1&l« Back](/help enchantments hover=Back to Enchantments)

    'enchantments sting':
      - |
        **Sting**
        ##Poisons the target##

        Rarity: &2Uncommon&r
        Max Level: III
        Found on: Swords, Axes
        Enchantable on: Swords, Axes
        Conflicts with: Fire Aspect, Frost

        [&1&l« Back](/help enchantments hover=Back to Enchantments)

    'enchantments spectral':
      - |
        **Spectral**
        ##Make the target glow##

        Rarity: &1Rare&r
        Max Level: III
        Found on: Swords, Axes
        Enchantable on: Swords, Axes

        [&1&l« Back](/help enchantments hover=)

    'enchantments harvest':
      - |
        **Harvest**
        ##Automatically replants crops.##

        Rarity: &1Rare&r
        Max Level: I
        Found on: Hoes
        Enchantable on: Hoes

        [&1&l« Back](/help enchantments hover=)

    'enchantments sniper':
      - |
        **Sniper**
        ##Fire arrows faster and further##

        Rarity: &1Rare&r
        Max Level: III
        Found on: Bows, Crossbows
        Enchantable on: Bows, Crossbows

        [&1&l« Back](/help enchantments hover=Back to Enchantments)

    'enchantments parry':
      - |
        **Parry**
        ##Grants Strength after blocking a hit##

        Rarity: &1Uncommon&r
        Max Level: II
        Found on: Shields
        Enchantable on: Shields

        [&1&l« Back](/help enchantments hover=Back to Enchantments)

    'enchantments rush':
      - |
        **Rush**
        ##Grants Speed after blocking a hit##

        Rarity: &1Uncommon&r
        Max Level: II
        Found on: Shields
        Enchantable on: Shields

        [&1&l« Back](/help enchantments hover=Back to Enchantments)

    'enchantments final':
      - |
        **Final**
        ##Cannot be modified on an anvil.##

        Rarity: &4Unique&r
        Found on: None
        Enchantable on: All

        [&1&l« Back](/help enchantments hover=Back to Enchantments)

