package me.weiwen.blanktopia.triggers

enum class TriggerType {
    RIGHT_CLICK_AIR,
    RIGHT_CLICK_BLOCK,
    RIGHT_CLICK_ENTITY,

    LEFT_CLICK_AIR,
    LEFT_CLICK_BLOCK,

    MIDDLE_CLICK_AIR,
    MIDDLE_CLICK_BLOCK,

    DAMAGE_ENTITY,

    EQUIP_ARMOR,
    UNEQUIP_ARMOR,
    EQUIP_HEAD,
    EQUIP_CHEST,
    EQUIP_LEGS,
    EQUIP_FEET,

    CONSUME,

    BREAK_BLOCK,
    PLACE_BLOCK,
    DROP,

    RIGHT_CLICK_INVENTORY,
    LEFT_CLICK_INVENTORY,
    MIDDLE_CLICK_INVENTORY,
    SHIFT_RIGHT_CLICK_INVENTORY,
    SHIFT_LEFT_CLICK_INVENTORY,
    DOUBLE_CLICK_INVENTORY,
    DROP_INVENTORY,
    CONTROL_DROP_INVENTORY,
    LEFT_BORDER_INVENTORY,
    RIGHT_BORDER_INVENTORY,
    NUMBER_KEY_1_INVENTORY,
    NUMBER_KEY_2_INVENTORY,
    NUMBER_KEY_3_INVENTORY,
    NUMBER_KEY_4_INVENTORY,
    NUMBER_KEY_5_INVENTORY,
    NUMBER_KEY_6_INVENTORY,
    NUMBER_KEY_7_INVENTORY,
    NUMBER_KEY_8_INVENTORY,
    NUMBER_KEY_9_INVENTORY,
    CREATIVE_INVENTORY,
    SWAP_OFFHAND_INVENTORY,

    MOVE,
    JUMP,
    SNEAK,
    UNSNEAK,
    SPRINT,
    UNSPRINT,
    FLY,
    UNFLY,
    GLIDE,
    UNGLIDE,
    SWIM,
    UNSWIM,
}

val EQUIPPED_TRIGGERS = setOf(
    TriggerType.MOVE,
    TriggerType.JUMP,
    TriggerType.SNEAK,
    TriggerType.UNSNEAK,
    TriggerType.SPRINT,
    TriggerType.UNSPRINT,
    TriggerType.FLY,
    TriggerType.UNFLY,
    TriggerType.GLIDE,
    TriggerType.UNGLIDE,
    TriggerType.SWIM,
    TriggerType.UNSWIM
)
