use-crafting-table-and-ender-chest-from-inventory: true

disable-crop-trampling: true

pet-teleport-together: false

single-player-sleep: true

ender-dragon-drops-elytra: true

shulkers-respawn: true
max-shulkers-per-chunk: 1
shulker-spawn-chance: 0.1

chestsort-hook: true